palette = "coolor"

format = """
[░▒▓](slate)\
[ ](bg:slate fg:sgreen)\
[](bg:sgreen fg:slate)\
[ ](bg:sgreen fg:slate)\
$username\
[](bg:slate fg:sgreen)\
$directory\
[](fg:slate bg:darkslate)\
$git_branch\
$git_status\
[](fg:darkslate bg:#)\
\n$character"""

right_format = """
$nodejs\
$rust\
$golang\
$php\

[](fg:slate)
$time\
[](fg:slate)\
$battery\
[](fg:slate)\
[](fg:slate)\
$cmd_duration\

"""

[palettes.coolor]
night = '#00120b'
darkslate = '#35605a'
ddslate = '#2b4f4a'
slate = '#6b818c'
lavender = '#d8e4ff'
sgreen = '#31e981'
mint = '#85e7c0'
pblue = '#a2b3c6'
mgreen = '#507173'
jade = '#33a56e'
pink = '#ff70fd'

[palettes.gren]
darkgreen = '#166446'
lightgreen = '#1d865e'
lightgray = '#e3e5e5'
darkgray = '#394260'

[username]
show_always = true
style_user = "fg:slate bg:sgreen"
style_root = "bg:#9A348E"
format = '[$user ]($style)'
disabled = false

[directory]
style = "fg:mint bg:slate"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

# GIT STUFF

[git_branch]
symbol = ""
style = "bg:night"
format = '[[ $symbol $branch ](fg:jade bg:darkslate)]($style)'

[git_status]
style = "bg:night"
format = '[[($all_status$ahead_behind )](fg:jade bg:darkslate)]($style)'

# LANGUAGES

[nodejs]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:pink bg:#212736)]($style)'

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:pink bg:#212736)]($style)'

[golang]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:pink bg:#212736)]($style)'

[python]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:pink bg:#212736)]($style)'

[c]
symbol = "c"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:pink bg:#212736)]($style)'

[haskell]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:pink bg:#212736)]($style)'

[lua]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:pink bg:#212736)]($style)'

[bun]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:pink bg:#212736)]($style)'

[php]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:slate bg:#212736)]($style)'


# UTILITIES

[os]
style = "bg:#9A348E"
disabled = true # Disabled by default

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:night bg:slate)]($style)'


[battery]
full_symbol = ' '
charging_symbol = '󱐋 '
discharging_symbol = '󱐌 '
style = "bg:#1d2230"
format = '[ $symbol$percentage ]($style)'

[[battery.display]]
threshold = 10
style = 'bold red'

[[battery.display]]
threshold = 50
style = 'bold yellow'

[[battery.display]]
threshold = 100
style = 'bold green'

[cmd_duration]
min_time = 1
format = 'took [$duration](bold yellow)'
